#!/bin/sh

GDB_64=gdb_aarch64
GDB_32=gdb_armhf

if ! ls /lib/ | grep -wq ld-linux-armhf.so && $GDB_64 -v &>/dev/null; then
	# Prefer aarch64 when armhf ld not exists.
	$GDB_64 $@
elif $GDB_32 -v &>/dev/null; then
	# Fallback to armhf
	$GDB_32 $@
else
	# Fallback to original
	/usr/bin/gdb $@
fi
