#!/bin/bash
# Usage: ./mk-partition.sh <max partition num> <default partition num>

RK_PARTITION_MAX_NUM=${1:-5}
RK_PARTITION_NUM=${2:-2}

cat <<EOF
# Auto generated by $0${@:+ $@}

menu "Extra partitions"

config RK_EXTRA_PARTITION_NUM
	int "number of extra partitions"
	range 0 $RK_PARTITION_MAX_NUM
	default $RK_PARTITION_NUM
EOF

unset RK_PARTITIONS
for i in $(seq 1 $RK_PARTITION_MAX_NUM); do
	cat <<EOF

config RK_EXTRA_PARTITION_$i
	bool "extra partition $i"
	depends on RK_EXTRA_PARTITION_NUM > $(( $i - 1 ))
	default y

if RK_EXTRA_PARTITION_$i

menu "Extra partition $i"

config RK_EXTRA_PARTITION_${i}_DEV
	string "device"
EOF
	case $i in
		1) echo -e "\tdefault \"oem\"" ;;
		2) echo -e "\tdefault \"userdata\"" ;;
	esac

	cat <<EOF

config RK_EXTRA_PARTITION_${i}_MOUNTPOINT
	string "mountpoint"
	default "/\$RK_EXTRA_PARTITION_${i}_DEV"

config RK_EXTRA_PARTITION_${i}_FSTYPE
	string "filesystem type"
	default "ext2"

config RK_EXTRA_PARTITION_${i}_OPTIONS
	string "mount options"
	default "defaults"

config RK_EXTRA_PARTITION_${i}_SRC
	string "source dirs"
EOF

	if [ $i -lt 3 ]; then
		cat << EOF
	default "\${RK_EXTRA_PARTITION_${i}_DEV}_empty" if RK_CHIP_FAMILY = "rk3308"
	default "\${RK_EXTRA_PARTITION_${i}_DEV}_normal"
EOF
	fi

	cat <<EOF

config RK_EXTRA_PARTITION_${i}_SIZE
	string "image size (size(M|K)|auto(0)|max)"
	default "auto"

config RK_EXTRA_PARTITION_${i}_BUILTIN
	bool "merged into rootfs"

config RK_EXTRA_PARTITION_${i}_FIXED
	bool "skip resizing"
	depends on !RK_EXTRA_PARTITION_${i}_BUILTIN
	default y if RK_EXTRA_PARTITION_${i}_FSTYPE = "ubi" || \\
		RK_EXTRA_PARTITION_${i}_FSTYPE = "ubifs"

config RK_EXTRA_PARTITION_${i}_FEATURES
	string
	default "\${RK_EXTRA_PARTITION_${i}_FIXED:+fixed,}\${RK_EXTRA_PARTITION_${i}_BUILTIN:+builtin}"

config RK_EXTRA_PARTITION_${i}_CFG
	string
	depends on RK_EXTRA_PARTITION_${i}_DEV != ""
	default "\$RK_EXTRA_PARTITION_${i}_DEV:\$RK_EXTRA_PARTITION_${i}_MOUNTPOINT:\$RK_EXTRA_PARTITION_${i}_FSTYPE:\$RK_EXTRA_PARTITION_${i}_OPTIONS:\${RK_EXTRA_PARTITION_${i}_SRC// /,}:\$RK_EXTRA_PARTITION_${i}_SIZE:\$RK_EXTRA_PARTITION_${i}_FEATURES"

endmenu # Extra partition $i

endif # RK_EXTRA_PARTITION_${i}
EOF

	RK_PARTITIONS="${RK_PARTITIONS:+${RK_PARTITIONS}@}\$RK_EXTRA_PARTITION_${i}_CFG"
done

cat << EOF

config RK_EXTRA_PARTITIONS
	string
	default "$RK_PARTITIONS"

endmenu # Extra partitions
EOF
